[tool.poetry]
name = "keymap-drawer"
version = "0.2.0"
description = "A module and CLI tool to help parse and draw keyboard layouts."
authors = ["Cem Aksoylar <caksoylar@gmail.com>"]
readme = ["README.md", "KEYMAP_SPEC.md"]
packages = [{include = "keymap_drawer"}]
license = "MIT"
homepage = "https://github.com/caksoylar/keymap-drawer"
repository = "https://github.com/caksoylar/keymap-drawer"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/caksoylar/keymap-drawer/issues"

[tool.poetry.dependencies]
python = "^3.10"
pydantic = "^1.10.2"
pcpp = "^1.30"
pyparsing = "^3.0.9"
pyyaml = "^6.0"

[tool.poetry.group.dev.dependencies]
mypy = "^1.0.0"
pylint = "^2.15.2"
black = "^22.8.0"
pylint-pydantic = "^0.1.4"
types-pyyaml = "^6.0.12.2"

[tool.poetry.group.lsp]
optional = true

[tool.poetry.group.lsp.dependencies]
python-lsp-server = "^1.6.0"

[tool.poetry.group.streamlit]
optional = true

[tool.poetry.group.streamlit.dependencies]
streamlit = "^1.17.0"

[tool.poetry.scripts]
keymap = 'keymap_drawer.__main__:main'

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pylint.MASTER]
extension-pkg-whitelist = "pydantic"
load-plugins = "pylint_pydantic"

[tool.pylint.'MESSAGES CONTROL']
disable = """
    too-few-public-methods,
"""

[tool.pylint.BASIC]
good-names = "x,y,w,h,r,f,k,p,m,c"
max-line-length = 120

[tool.mypy]
plugins = "pydantic.mypy"

[tool.black]
line-length = 120
